---
apiVersion: v1
kind: Namespace
metadata:
  name: dra-noop-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-noop-driver
  namespace: dra-noop-driver
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: dra-noop-driver
    app.kubernetes.io/name: dra-noop-driver
  name: dra-noop-driver-kubeletplugin
  namespace: dra-noop-driver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dra-noop-driver
      app.kubernetes.io/name: dra-noop-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dra-noop-driver
        app.kubernetes.io/name: dra-noop-driver
    spec:
      containers:
      - command:
        - /usr/bin/dra-noop-kubeletplugin
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: jondev.azurecr.io/dra-noop-driver:v1.32.0
        imagePullPolicy: IfNotPresent
        name: plugin
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins_registry
          name: plugins-registry
        - mountPath: /var/lib/kubelet/plugins
          name: plugins
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccountName: dra-noop-driver
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: ""
        name: plugins-registry
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: ""
        name: plugins
---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: imex.nvidia.com
spec:
  selectors:
  - cel:
      expression: device.driver == 'noop.example.com' && device.attributes["noop.example.com"].type == 'imex'
---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: gpu.nvidia.com
spec:
  selectors:
  - cel:
      expression: device.driver == 'noop.example.com' && device.attributes["noop.example.com"].type == 'gpu'
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: imex-0
spec:
  devices:
    - basic:
        attributes:
          type:
            string: imex
      name: imex-0
  driver: noop.example.com
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: imex-id
            operator: In
            values:
              - "0"
  pool:
    name: imex-0
    generation: 0
    resourceSliceCount: 1
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: imex-1
spec:
  devices:
    - basic:
        attributes:
          type:
            string: imex
      name: imex-1
  driver: noop.example.com
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: imex-id
            operator: In
            values:
              - "1"
  pool:
    name: imex-1
    generation: 0
    resourceSliceCount: 1
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: gpu-0
spec:
  devices:
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-0
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-1
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-2
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-3
  driver: noop.example.com
  nodeName: kind-worker
  pool:
    name: gpu-0
    generation: 0
    resourceSliceCount: 1
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: gpu-1
spec:
  devices:
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-0
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-1
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-2
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-3
  driver: noop.example.com
  nodeName: kind-worker2
  pool:
    name: gpu-1
    generation: 0
    resourceSliceCount: 1
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: gpu-2
spec:
  devices:
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-0
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-1
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-2
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-3
  driver: noop.example.com
  nodeName: kind-worker3
  pool:
    name: gpu-2
    generation: 0
    resourceSliceCount: 1
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: gpu-3
spec:
  devices:
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-0
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-1
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-2
    - basic:
        attributes:
          type:
            string: gpu
      name: gpu-3
  driver: noop.example.com
  nodeName: kind-worker4
  pool:
    name: gpu-3
    generation: 0
    resourceSliceCount: 1
