---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaim
metadata:
  namespace: test
  name: test-imex-claim
spec:
  devices:
    requests:
    - name: imex
      deviceClassName: imex.nvidia.com
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaim
metadata:
  namespace: test
  name: test-imex-claim-1
spec:
  devices:
    requests:
    - name: imex
      deviceClassName: imex.nvidia.com
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: test
  name: test-gpu-claim
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: test-deploy
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: imex
          - name: gpu
      resourceClaims:
      - name: imex
        resourceClaimName: test-imex-claim
      - name: gpu
        resourceClaimTemplateName: test-gpu-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: test-deploy-1
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: imex
          - name: gpu
      resourceClaims:
      - name: imex
        resourceClaimName: test-imex-claim-1
      - name: gpu
        resourceClaimTemplateName: test-gpu-claim
