# Common Resources
apiVersion: v1
kind: Namespace
metadata:
  name: test-no-dra
---

# Workload 1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-no-dra
  name: test-deploy-1
  labels:
    app: test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      affinity:
        # Ensure these Pods are running on Nodes with the same imex-id
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - test-1
            topologyKey: imex-id
        # Ensure other Pods are not running on Nodes with the same imex-id
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                    - test-1
            topologyKey: imex-id
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
---

# Workload 2
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-no-dra
  name: test-deploy-2
  labels:
    app: test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      affinity:
        # Ensure these Pods are running on Nodes with the same imex-id
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - test-2
            topologyKey: imex-id
        # Ensure other Pods are not running on Nodes with the same imex-id
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                    - test-2
            topologyKey: imex-id
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
